<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Basket.aspx.cs" Inherits="Food_Order_Website.Basket" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <asp:Label ID="welc" runat="server" Text="Label" Visible="false"></asp:Label>
    
    <asp:GridView ID="BasketGrid" runat="server" Width="100%" AutoGenerateDeleteButton="True" OnRowDeleting="BasketGrid_RowDeleting" BackColor="#DEBA84" BorderColor="#DEBA84" BorderStyle="None" BorderWidth="1px" CellPadding="3" CellSpacing="2">
        <FooterStyle BackColor="#F7DFB5" ForeColor="#8C4510" />
        <HeaderStyle BackColor="#A55129" Font-Bold="True" ForeColor="White" />
        <PagerStyle ForeColor="#8C4510" HorizontalAlign="Center" />
        <RowStyle BackColor="#FFF7E7" ForeColor="#8C4510" />
        <SelectedRowStyle BackColor="#738A9C" Font-Bold="True" ForeColor="White" />
        <SortedAscendingCellStyle BackColor="#FFF1D4" />
        <SortedAscendingHeaderStyle BackColor="#B95C30" />
        <SortedDescendingCellStyle BackColor="#F1E5CE" />
        <SortedDescendingHeaderStyle BackColor="#93451F" />
    </asp:GridView>
    <div><asp:Label ID="noteID" runat="server" Text="Sipariş Notu :" Visible="False"></asp:Label></div>
    
    <asp:TextBox ID="TextBoxNoteID" runat="server" Height="25px" Width="504px"></asp:TextBox>
    
    <asp:RadioButtonList ID="payementType" runat="server" Visible="False" Height="16px" Width="43px">
        <asp:ListItem Value="kredi">Kredi Kartı</asp:ListItem>
        <asp:ListItem Value="nakit" Selected="True">Nakit</asp:ListItem>
    </asp:RadioButtonList>
    <asp:ImageButton ID="acceptButtonImage" runat="server" Height="93px" ImageUrl="~/images/2000px-Accept.svg.png" OnClick="acceptButtonImage_Click" Width="114px" />
    
</asp:Content>
